#!/usr/bin/with-contenv bash

for s in /assets/functions/*; do source $s; done
PROCESS_NAME="traefik-cloudflare-companion"

check_container_initialized
check_service_initialized init
liftoff

print_info "Starting Traefik Cloudflare Companion"
exec python -u /usr/sbin/cloudflare-companion
