#!/usr/bin/with-contenv bash

source /assets/functions/*
PROCESS_NAME="traefik-cloudflare-companion"
check_initialized
liftoff

print_info "Starting Traefik Cloudflare Companion"
exec python -u /usr/sbin/cloudflare-companion
