#!/command/with-contenv bash

source /assets/functions/00-container
prepare_service defaults single
PROCESS_NAME="traefik-cloudflare-companion"

check_container_initialized
check_service_initialized init

# Delay service startup by specified seconds   
RUN_DELAY="${RUN_DELAY:=0}"
if [[ ${RUN_DELAY} -gt 0 ]]; then
    print_info "Delaying service startup by ${RUN_DELAY} seconds"
    sleep "${RUN_DELAY}"
fi

liftoff

print_start "Starting Traefik Cloudflare Companion"
exec s6-setuidgid "${TCC_USER}" \
                                python3 \
                                        -u /usr/sbin/cloudflare-companion
